# Generated by Django 4.2.9 on 2024-01-28 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count_cooked', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('count_cooked',),
            },
        ),
        migrations.CreateModel(
            name='ProductInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1 грамм')], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.product', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингридиент для рецепта',
                'verbose_name_plural': 'Ингридиенты для рецепта',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название рецепта')),
                ('products', models.ManyToManyField(related_name='recipes', through='cookbook.ProductInRecipe', to='cookbook.product', verbose_name='Ингридиенты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='productinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='productinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'product'), name='unique_product'),
        ),
    ]
